import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
const mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Abhinav Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { session, ...params },
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen justify-between  ${mont.className}`}>
        <div className=" md:px-60 ">
          <NavBar />
          <div className="flex-grow">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
